<?xml version="1.0" encoding="utf-8"?><Database Name="QLWEBTICKETMOVIES" Class="DataWebDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=DESKTOP-9SAS8HE\VITAMINCO;Initial Catalog=QLWEBTICKETMOVIES;Persist Security Info=True;User ID=sa" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="QLWEBTICKETMOVIESConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.CAUHINH" Member="CAUHINHs">
    <Type Name="CAUHINH">
      <Column Name="IDCAUHINH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GIATRI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.HINHANH" Member="HINHANHs">
    <Type Name="HINHANH">
      <Column Name="IDHINHANH" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HINHANHTAIKHOANG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOGO" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HINHANHPHIM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HINHANHSUKIEN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HINHANHBAIVIET" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HINHANHGIOITHIEU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDTAIKHOANGTHANHVIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HINHANHBANNER" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="HINHANH_KHUYENMAI" Member="KHUYENMAIs" ThisKey="IDHINHANH" OtherKey="IDHINHANH" Type="KHUYENMAI" />
    </Type>
  </Table>
  <Table Name="dbo.KHUYENMAI" Member="KHUYENMAIs">
    <Type Name="KHUYENMAI">
      <Column Name="IDKHUYENMAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CHUDEKHUYENMAI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MUCUUDAI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NOIDUNG" Type="System.String" DbType="NVarChar(1000) NOT NULL" CanBeNull="false" />
      <Column Name="NGAYBANHANH" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="NGAYKETTHUC" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="IDCACBOPHIM" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDHINHANH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="HINHANHKHUYENMAI" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="HINHANH_KHUYENMAI" Member="HINHANH" ThisKey="IDHINHANH" OtherKey="IDHINHANH" Type="HINHANH" IsForeignKey="true" />
      <Association Name="PHIM_KHUYENMAI" Member="PHIM" ThisKey="IDCACBOPHIM" OtherKey="IDCACBOPHIM" Type="PHIM" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.THELOAIPHIM" Member="THELOAIPHIMs">
    <Type Name="THELOAIPHIM">
      <Column Name="IDLOAI" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="LOAIPHIM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="THELOAIPHIM" Member="THELOAIPHIM1" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="THELOAIPHIM_PHIM" Member="PHIMs" ThisKey="IDLOAI" OtherKey="IDLOAI" Type="PHIM" />
    </Type>
  </Table>
  <Table Name="dbo.TINTUC" Member="TINTUCs">
    <Type Name="TINTUC">
      <Column Name="IDTIN" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENTIN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NOIDUNG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="THOIGIAN" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="HINHANH" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="DIADIEM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DIEUKHOANG" Member="DIEUKHOANGs">
    <Type Name="DIEUKHOANG">
      <Column Name="IDDIEUKHOANG" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="TENDIEUKHOANG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NOIDUNGDIEUKHOANG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIOITHIEU" Member="GIOITHIEUs">
    <Type Name="GIOITHIEU">
      <Column Name="IDGIOITHIEU" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HINHANHGIOITHIEU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NOIDUNGGIOITHIEU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.GIAVE" Member="GIAVEs">
    <Type Name="GIAVE">
      <Column Name="IDGIAVE" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="HINHGIAVE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="LOAIPHIM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TENNBANGVE" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.PHIM" Member="PHIMs">
    <Type Name="PHIM">
      <Column Name="IDCACBOPHIM" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDLOAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGDAYDANG" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IDTAIKHOANGTINVIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GIAGIAM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TENPHIM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NOIDUNGPHIM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MAPHONG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XUATCHIEU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VIDEOS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HINHANHPHIM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="THOILUONG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Association Name="PHIM_KHUYENMAI" Member="KHUYENMAIs" ThisKey="IDCACBOPHIM" OtherKey="IDCACBOPHIM" Type="KHUYENMAI" />
      <Association Name="THELOAIPHIM_PHIM" Member="THELOAIPHIM" ThisKey="IDLOAI" OtherKey="IDLOAI" Type="THELOAIPHIM" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Function Name="dbo.PHIMANDTHEOAI" Method="PHIMANDTHEOAI">
    <ElementType Name="PHIMANDTHEOAIResult">
      <Column Name="IDCACBOPHIM" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="GHICHU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDLOAI" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IDHINHANH" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NGDAYDANG" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="IDTAIKHOANGTINVIEN" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="GIABAN" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="GIAGIAM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="TENPHIM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="NOIDUNGPHIM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="MAPHONG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="XUATCHIEU" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="VIDEOS" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="HINHANHPHIM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="THOILUONG" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="IDLOAI1" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="LOAIPHIM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
      <Column Name="THELOAIPHIM" Type="System.String" DbType="NVarChar(MAX)" CanBeNull="true" />
    </ElementType>
  </Function>
</Database>