#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Linq;
using System.Data.Linq.Mapping;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;



[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLWEBTICKETMOVIES")]
public partial class DataWebDataContext : System.Data.Linq.DataContext
{
	
	private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
	
  #region Extensibility Method Definitions
  partial void OnCreated();
  partial void InsertHINHANH(HINHANH instance);
  partial void UpdateHINHANH(HINHANH instance);
  partial void DeleteHINHANH(HINHANH instance);
  partial void InsertCHITIETPHIM(CHITIETPHIM instance);
  partial void UpdateCHITIETPHIM(CHITIETPHIM instance);
  partial void DeleteCHITIETPHIM(CHITIETPHIM instance);
  partial void InsertTINTUC(TINTUC instance);
  partial void UpdateTINTUC(TINTUC instance);
  partial void DeleteTINTUC(TINTUC instance);
  partial void InsertPHIM(PHIM instance);
  partial void UpdatePHIM(PHIM instance);
  partial void DeletePHIM(PHIM instance);
  partial void InsertKHUYENMAI(KHUYENMAI instance);
  partial void UpdateKHUYENMAI(KHUYENMAI instance);
  partial void DeleteKHUYENMAI(KHUYENMAI instance);
  #endregion
	
	public DataWebDataContext() : 
			base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLWEBTICKETMOVIESConnectionString"].ConnectionString, mappingSource)
	{
		OnCreated();
	}
	
	public DataWebDataContext(string connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataWebDataContext(System.Data.IDbConnection connection) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataWebDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public DataWebDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
			base(connection, mappingSource)
	{
		OnCreated();
	}
	
	public System.Data.Linq.Table<HINHANH> HINHANHs
	{
		get
		{
			return this.GetTable<HINHANH>();
		}
	}
	
	public System.Data.Linq.Table<CHITIETPHIM> CHITIETPHIMs
	{
		get
		{
			return this.GetTable<CHITIETPHIM>();
		}
	}
	
	public System.Data.Linq.Table<TINTUC> TINTUCs
	{
		get
		{
			return this.GetTable<TINTUC>();
		}
	}
	
	public System.Data.Linq.Table<PHIM> PHIMs
	{
		get
		{
			return this.GetTable<PHIM>();
		}
	}
	
	public System.Data.Linq.Table<KHUYENMAI> KHUYENMAIs
	{
		get
		{
			return this.GetTable<KHUYENMAI>();
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HINHANH")]
public partial class HINHANH : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDHINHANH;
	
	private string _HINHANHTAIKHOANG;
	
	private string _LOGO;
	
	private string _HINHANHPHIM;
	
	private string _HINHANHSUKIEN;
	
	private string _HINHANHBAIVIET;
	
	private string _HINHANHGIOITHIEU;
	
	private System.Nullable<int> _IDTAIKHOANGTHANHVIEN;
	
	private string _HINHANHBANNER;
	
	private EntitySet<CHITIETPHIM> _CHITIETPHIMs;
	
	private EntitySet<PHIM> _PHIMs;
	
	private EntitySet<KHUYENMAI> _KHUYENMAIs;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHINHANHChanging(int value);
    partial void OnIDHINHANHChanged();
    partial void OnHINHANHTAIKHOANGChanging(string value);
    partial void OnHINHANHTAIKHOANGChanged();
    partial void OnLOGOChanging(string value);
    partial void OnLOGOChanged();
    partial void OnHINHANHPHIMChanging(string value);
    partial void OnHINHANHPHIMChanged();
    partial void OnHINHANHSUKIENChanging(string value);
    partial void OnHINHANHSUKIENChanged();
    partial void OnHINHANHBAIVIETChanging(string value);
    partial void OnHINHANHBAIVIETChanged();
    partial void OnHINHANHGIOITHIEUChanging(string value);
    partial void OnHINHANHGIOITHIEUChanged();
    partial void OnIDTAIKHOANGTHANHVIENChanging(System.Nullable<int> value);
    partial void OnIDTAIKHOANGTHANHVIENChanged();
    partial void OnHINHANHBANNERChanging(string value);
    partial void OnHINHANHBANNERChanged();
    #endregion
	
	public HINHANH()
	{
		this._CHITIETPHIMs = new EntitySet<CHITIETPHIM>(new Action<CHITIETPHIM>(this.attach_CHITIETPHIMs), new Action<CHITIETPHIM>(this.detach_CHITIETPHIMs));
		this._PHIMs = new EntitySet<PHIM>(new Action<PHIM>(this.attach_PHIMs), new Action<PHIM>(this.detach_PHIMs));
		this._KHUYENMAIs = new EntitySet<KHUYENMAI>(new Action<KHUYENMAI>(this.attach_KHUYENMAIs), new Action<KHUYENMAI>(this.detach_KHUYENMAIs));
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHINHANH", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDHINHANH
	{
		get
		{
			return this._IDHINHANH;
		}
		set
		{
			if ((this._IDHINHANH != value))
			{
				this.OnIDHINHANHChanging(value);
				this.SendPropertyChanging();
				this._IDHINHANH = value;
				this.SendPropertyChanged("IDHINHANH");
				this.OnIDHINHANHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANHTAIKHOANG", DbType="NVarChar(MAX)")]
	public string HINHANHTAIKHOANG
	{
		get
		{
			return this._HINHANHTAIKHOANG;
		}
		set
		{
			if ((this._HINHANHTAIKHOANG != value))
			{
				this.OnHINHANHTAIKHOANGChanging(value);
				this.SendPropertyChanging();
				this._HINHANHTAIKHOANG = value;
				this.SendPropertyChanged("HINHANHTAIKHOANG");
				this.OnHINHANHTAIKHOANGChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LOGO", DbType="NVarChar(MAX)")]
	public string LOGO
	{
		get
		{
			return this._LOGO;
		}
		set
		{
			if ((this._LOGO != value))
			{
				this.OnLOGOChanging(value);
				this.SendPropertyChanging();
				this._LOGO = value;
				this.SendPropertyChanged("LOGO");
				this.OnLOGOChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANHPHIM", DbType="NVarChar(MAX)")]
	public string HINHANHPHIM
	{
		get
		{
			return this._HINHANHPHIM;
		}
		set
		{
			if ((this._HINHANHPHIM != value))
			{
				this.OnHINHANHPHIMChanging(value);
				this.SendPropertyChanging();
				this._HINHANHPHIM = value;
				this.SendPropertyChanged("HINHANHPHIM");
				this.OnHINHANHPHIMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANHSUKIEN", DbType="NVarChar(MAX)")]
	public string HINHANHSUKIEN
	{
		get
		{
			return this._HINHANHSUKIEN;
		}
		set
		{
			if ((this._HINHANHSUKIEN != value))
			{
				this.OnHINHANHSUKIENChanging(value);
				this.SendPropertyChanging();
				this._HINHANHSUKIEN = value;
				this.SendPropertyChanged("HINHANHSUKIEN");
				this.OnHINHANHSUKIENChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANHBAIVIET", DbType="NVarChar(MAX)")]
	public string HINHANHBAIVIET
	{
		get
		{
			return this._HINHANHBAIVIET;
		}
		set
		{
			if ((this._HINHANHBAIVIET != value))
			{
				this.OnHINHANHBAIVIETChanging(value);
				this.SendPropertyChanging();
				this._HINHANHBAIVIET = value;
				this.SendPropertyChanged("HINHANHBAIVIET");
				this.OnHINHANHBAIVIETChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANHGIOITHIEU", DbType="NVarChar(MAX)")]
	public string HINHANHGIOITHIEU
	{
		get
		{
			return this._HINHANHGIOITHIEU;
		}
		set
		{
			if ((this._HINHANHGIOITHIEU != value))
			{
				this.OnHINHANHGIOITHIEUChanging(value);
				this.SendPropertyChanging();
				this._HINHANHGIOITHIEU = value;
				this.SendPropertyChanged("HINHANHGIOITHIEU");
				this.OnHINHANHGIOITHIEUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTAIKHOANGTHANHVIEN", DbType="Int")]
	public System.Nullable<int> IDTAIKHOANGTHANHVIEN
	{
		get
		{
			return this._IDTAIKHOANGTHANHVIEN;
		}
		set
		{
			if ((this._IDTAIKHOANGTHANHVIEN != value))
			{
				this.OnIDTAIKHOANGTHANHVIENChanging(value);
				this.SendPropertyChanging();
				this._IDTAIKHOANGTHANHVIEN = value;
				this.SendPropertyChanged("IDTAIKHOANGTHANHVIEN");
				this.OnIDTAIKHOANGTHANHVIENChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANHBANNER", DbType="NVarChar(MAX)")]
	public string HINHANHBANNER
	{
		get
		{
			return this._HINHANHBANNER;
		}
		set
		{
			if ((this._HINHANHBANNER != value))
			{
				this.OnHINHANHBANNERChanging(value);
				this.SendPropertyChanging();
				this._HINHANHBANNER = value;
				this.SendPropertyChanged("HINHANHBANNER");
				this.OnHINHANHBANNERChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HINHANH_CHITIETPHIM", Storage="_CHITIETPHIMs", ThisKey="IDHINHANH", OtherKey="IDHINHANH")]
	public EntitySet<CHITIETPHIM> CHITIETPHIMs
	{
		get
		{
			return this._CHITIETPHIMs;
		}
		set
		{
			this._CHITIETPHIMs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HINHANH_PHIM", Storage="_PHIMs", ThisKey="IDHINHANH", OtherKey="IDHINHANH")]
	public EntitySet<PHIM> PHIMs
	{
		get
		{
			return this._PHIMs;
		}
		set
		{
			this._PHIMs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HINHANH_KHUYENMAI", Storage="_KHUYENMAIs", ThisKey="IDHINHANH", OtherKey="IDHINHANH")]
	public EntitySet<KHUYENMAI> KHUYENMAIs
	{
		get
		{
			return this._KHUYENMAIs;
		}
		set
		{
			this._KHUYENMAIs.Assign(value);
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_CHITIETPHIMs(CHITIETPHIM entity)
	{
		this.SendPropertyChanging();
		entity.HINHANH = this;
	}
	
	private void detach_CHITIETPHIMs(CHITIETPHIM entity)
	{
		this.SendPropertyChanging();
		entity.HINHANH = null;
	}
	
	private void attach_PHIMs(PHIM entity)
	{
		this.SendPropertyChanging();
		entity.HINHANH = this;
	}
	
	private void detach_PHIMs(PHIM entity)
	{
		this.SendPropertyChanging();
		entity.HINHANH = null;
	}
	
	private void attach_KHUYENMAIs(KHUYENMAI entity)
	{
		this.SendPropertyChanging();
		entity.HINHANH = this;
	}
	
	private void detach_KHUYENMAIs(KHUYENMAI entity)
	{
		this.SendPropertyChanging();
		entity.HINHANH = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETPHIM")]
public partial class CHITIETPHIM : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDPHIM;
	
	private string _TENPHIM;
	
	private string _THONGTINPHIM;
	
	private string _MAPHONG;
	
	private string _MAPHIM;
	
	private System.Nullable<System.DateTime> _XUATCHIEU;
	
	private string _GHICHU;
	
	private System.Nullable<int> _IDHINHANH;
	
	private System.Nullable<int> _IDMOVIE;
	
	private EntityRef<HINHANH> _HINHANH;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDPHIMChanging(int value);
    partial void OnIDPHIMChanged();
    partial void OnTENPHIMChanging(string value);
    partial void OnTENPHIMChanged();
    partial void OnTHONGTINPHIMChanging(string value);
    partial void OnTHONGTINPHIMChanged();
    partial void OnMAPHONGChanging(string value);
    partial void OnMAPHONGChanged();
    partial void OnMAPHIMChanging(string value);
    partial void OnMAPHIMChanged();
    partial void OnXUATCHIEUChanging(System.Nullable<System.DateTime> value);
    partial void OnXUATCHIEUChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    partial void OnIDHINHANHChanging(System.Nullable<int> value);
    partial void OnIDHINHANHChanged();
    partial void OnIDMOVIEChanging(System.Nullable<int> value);
    partial void OnIDMOVIEChanged();
    #endregion
	
	public CHITIETPHIM()
	{
		this._HINHANH = default(EntityRef<HINHANH>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDPHIM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDPHIM
	{
		get
		{
			return this._IDPHIM;
		}
		set
		{
			if ((this._IDPHIM != value))
			{
				this.OnIDPHIMChanging(value);
				this.SendPropertyChanging();
				this._IDPHIM = value;
				this.SendPropertyChanged("IDPHIM");
				this.OnIDPHIMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENPHIM", DbType="NVarChar(MAX)")]
	public string TENPHIM
	{
		get
		{
			return this._TENPHIM;
		}
		set
		{
			if ((this._TENPHIM != value))
			{
				this.OnTENPHIMChanging(value);
				this.SendPropertyChanging();
				this._TENPHIM = value;
				this.SendPropertyChanged("TENPHIM");
				this.OnTENPHIMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THONGTINPHIM", DbType="NVarChar(MAX)")]
	public string THONGTINPHIM
	{
		get
		{
			return this._THONGTINPHIM;
		}
		set
		{
			if ((this._THONGTINPHIM != value))
			{
				this.OnTHONGTINPHIMChanging(value);
				this.SendPropertyChanging();
				this._THONGTINPHIM = value;
				this.SendPropertyChanged("THONGTINPHIM");
				this.OnTHONGTINPHIMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHONG", DbType="NVarChar(MAX)")]
	public string MAPHONG
	{
		get
		{
			return this._MAPHONG;
		}
		set
		{
			if ((this._MAPHONG != value))
			{
				this.OnMAPHONGChanging(value);
				this.SendPropertyChanging();
				this._MAPHONG = value;
				this.SendPropertyChanged("MAPHONG");
				this.OnMAPHONGChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHIM", DbType="NVarChar(MAX)")]
	public string MAPHIM
	{
		get
		{
			return this._MAPHIM;
		}
		set
		{
			if ((this._MAPHIM != value))
			{
				this.OnMAPHIMChanging(value);
				this.SendPropertyChanging();
				this._MAPHIM = value;
				this.SendPropertyChanged("MAPHIM");
				this.OnMAPHIMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XUATCHIEU", DbType="DateTime")]
	public System.Nullable<System.DateTime> XUATCHIEU
	{
		get
		{
			return this._XUATCHIEU;
		}
		set
		{
			if ((this._XUATCHIEU != value))
			{
				this.OnXUATCHIEUChanging(value);
				this.SendPropertyChanging();
				this._XUATCHIEU = value;
				this.SendPropertyChanged("XUATCHIEU");
				this.OnXUATCHIEUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(MAX)")]
	public string GHICHU
	{
		get
		{
			return this._GHICHU;
		}
		set
		{
			if ((this._GHICHU != value))
			{
				this.OnGHICHUChanging(value);
				this.SendPropertyChanging();
				this._GHICHU = value;
				this.SendPropertyChanged("GHICHU");
				this.OnGHICHUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHINHANH", DbType="Int")]
	public System.Nullable<int> IDHINHANH
	{
		get
		{
			return this._IDHINHANH;
		}
		set
		{
			if ((this._IDHINHANH != value))
			{
				if (this._HINHANH.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDHINHANHChanging(value);
				this.SendPropertyChanging();
				this._IDHINHANH = value;
				this.SendPropertyChanged("IDHINHANH");
				this.OnIDHINHANHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDMOVIE", DbType="Int")]
	public System.Nullable<int> IDMOVIE
	{
		get
		{
			return this._IDMOVIE;
		}
		set
		{
			if ((this._IDMOVIE != value))
			{
				this.OnIDMOVIEChanging(value);
				this.SendPropertyChanging();
				this._IDMOVIE = value;
				this.SendPropertyChanged("IDMOVIE");
				this.OnIDMOVIEChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HINHANH_CHITIETPHIM", Storage="_HINHANH", ThisKey="IDHINHANH", OtherKey="IDHINHANH", IsForeignKey=true, DeleteRule="CASCADE")]
	public HINHANH HINHANH
	{
		get
		{
			return this._HINHANH.Entity;
		}
		set
		{
			HINHANH previousValue = this._HINHANH.Entity;
			if (((previousValue != value) 
						|| (this._HINHANH.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._HINHANH.Entity = null;
					previousValue.CHITIETPHIMs.Remove(this);
				}
				this._HINHANH.Entity = value;
				if ((value != null))
				{
					value.CHITIETPHIMs.Add(this);
					this._IDHINHANH = value.IDHINHANH;
				}
				else
				{
					this._IDHINHANH = default(Nullable<int>);
				}
				this.SendPropertyChanged("HINHANH");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.TINTUC")]
public partial class TINTUC : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDTIN;
	
	private string _TENTIN;
	
	private string _NOIDUNG;
	
	private System.Nullable<System.DateTime> _THOIGIAN;
	
	private string _HINHANH;
	
	private string _DIADIEM;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDTINChanging(int value);
    partial void OnIDTINChanged();
    partial void OnTENTINChanging(string value);
    partial void OnTENTINChanged();
    partial void OnNOIDUNGChanging(string value);
    partial void OnNOIDUNGChanged();
    partial void OnTHOIGIANChanging(System.Nullable<System.DateTime> value);
    partial void OnTHOIGIANChanged();
    partial void OnHINHANHChanging(string value);
    partial void OnHINHANHChanged();
    partial void OnDIADIEMChanging(string value);
    partial void OnDIADIEMChanged();
    #endregion
	
	public TINTUC()
	{
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTIN", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDTIN
	{
		get
		{
			return this._IDTIN;
		}
		set
		{
			if ((this._IDTIN != value))
			{
				this.OnIDTINChanging(value);
				this.SendPropertyChanging();
				this._IDTIN = value;
				this.SendPropertyChanged("IDTIN");
				this.OnIDTINChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENTIN", DbType="NVarChar(MAX)")]
	public string TENTIN
	{
		get
		{
			return this._TENTIN;
		}
		set
		{
			if ((this._TENTIN != value))
			{
				this.OnTENTINChanging(value);
				this.SendPropertyChanging();
				this._TENTIN = value;
				this.SendPropertyChanged("TENTIN");
				this.OnTENTINChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG", DbType="NVarChar(MAX)")]
	public string NOIDUNG
	{
		get
		{
			return this._NOIDUNG;
		}
		set
		{
			if ((this._NOIDUNG != value))
			{
				this.OnNOIDUNGChanging(value);
				this.SendPropertyChanging();
				this._NOIDUNG = value;
				this.SendPropertyChanged("NOIDUNG");
				this.OnNOIDUNGChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_THOIGIAN", DbType="Date")]
	public System.Nullable<System.DateTime> THOIGIAN
	{
		get
		{
			return this._THOIGIAN;
		}
		set
		{
			if ((this._THOIGIAN != value))
			{
				this.OnTHOIGIANChanging(value);
				this.SendPropertyChanging();
				this._THOIGIAN = value;
				this.SendPropertyChanged("THOIGIAN");
				this.OnTHOIGIANChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANH", DbType="NVarChar(MAX)")]
	public string HINHANH
	{
		get
		{
			return this._HINHANH;
		}
		set
		{
			if ((this._HINHANH != value))
			{
				this.OnHINHANHChanging(value);
				this.SendPropertyChanging();
				this._HINHANH = value;
				this.SendPropertyChanged("HINHANH");
				this.OnHINHANHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DIADIEM", DbType="NVarChar(MAX)")]
	public string DIADIEM
	{
		get
		{
			return this._DIADIEM;
		}
		set
		{
			if ((this._DIADIEM != value))
			{
				this.OnDIADIEMChanging(value);
				this.SendPropertyChanging();
				this._DIADIEM = value;
				this.SendPropertyChanged("DIADIEM");
				this.OnDIADIEMChanged();
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.PHIM")]
public partial class PHIM : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDCACBOPHIM;
	
	private string _GHICHU;
	
	private System.Nullable<int> _IDLOAI;
	
	private System.Nullable<int> _IDHINHANH;
	
	private System.Nullable<System.DateTime> _NGDAYDANG;
	
	private System.Nullable<int> _IDTAIKHOANGTINVIEN;
	
	private string _GIABAN;
	
	private string _GIAGIAM;
	
	private string _TENPHIM;
	
	private string _NOIDUNGPHIM;
	
	private string _MAPHONG;
	
	private string _XUATCHIEU;
	
	private string _VIDEOS;
	
	private string _HINHANHPHIM;
	
	private EntitySet<KHUYENMAI> _KHUYENMAIs;
	
	private EntityRef<HINHANH> _HINHANH;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDCACBOPHIMChanging(int value);
    partial void OnIDCACBOPHIMChanged();
    partial void OnGHICHUChanging(string value);
    partial void OnGHICHUChanged();
    partial void OnIDLOAIChanging(System.Nullable<int> value);
    partial void OnIDLOAIChanged();
    partial void OnIDHINHANHChanging(System.Nullable<int> value);
    partial void OnIDHINHANHChanged();
    partial void OnNGDAYDANGChanging(System.Nullable<System.DateTime> value);
    partial void OnNGDAYDANGChanged();
    partial void OnIDTAIKHOANGTINVIENChanging(System.Nullable<int> value);
    partial void OnIDTAIKHOANGTINVIENChanged();
    partial void OnGIABANChanging(string value);
    partial void OnGIABANChanged();
    partial void OnGIAGIAMChanging(string value);
    partial void OnGIAGIAMChanged();
    partial void OnTENPHIMChanging(string value);
    partial void OnTENPHIMChanged();
    partial void OnNOIDUNGPHIMChanging(string value);
    partial void OnNOIDUNGPHIMChanged();
    partial void OnMAPHONGChanging(string value);
    partial void OnMAPHONGChanged();
    partial void OnXUATCHIEUChanging(string value);
    partial void OnXUATCHIEUChanged();
    partial void OnVIDEOSChanging(string value);
    partial void OnVIDEOSChanged();
    partial void OnHINHANHPHIMChanging(string value);
    partial void OnHINHANHPHIMChanged();
    #endregion
	
	public PHIM()
	{
		this._KHUYENMAIs = new EntitySet<KHUYENMAI>(new Action<KHUYENMAI>(this.attach_KHUYENMAIs), new Action<KHUYENMAI>(this.detach_KHUYENMAIs));
		this._HINHANH = default(EntityRef<HINHANH>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCACBOPHIM", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDCACBOPHIM
	{
		get
		{
			return this._IDCACBOPHIM;
		}
		set
		{
			if ((this._IDCACBOPHIM != value))
			{
				this.OnIDCACBOPHIMChanging(value);
				this.SendPropertyChanging();
				this._IDCACBOPHIM = value;
				this.SendPropertyChanged("IDCACBOPHIM");
				this.OnIDCACBOPHIMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GHICHU", DbType="NVarChar(MAX)")]
	public string GHICHU
	{
		get
		{
			return this._GHICHU;
		}
		set
		{
			if ((this._GHICHU != value))
			{
				this.OnGHICHUChanging(value);
				this.SendPropertyChanging();
				this._GHICHU = value;
				this.SendPropertyChanged("GHICHU");
				this.OnGHICHUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDLOAI", DbType="Int")]
	public System.Nullable<int> IDLOAI
	{
		get
		{
			return this._IDLOAI;
		}
		set
		{
			if ((this._IDLOAI != value))
			{
				this.OnIDLOAIChanging(value);
				this.SendPropertyChanging();
				this._IDLOAI = value;
				this.SendPropertyChanged("IDLOAI");
				this.OnIDLOAIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHINHANH", DbType="Int")]
	public System.Nullable<int> IDHINHANH
	{
		get
		{
			return this._IDHINHANH;
		}
		set
		{
			if ((this._IDHINHANH != value))
			{
				if (this._HINHANH.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDHINHANHChanging(value);
				this.SendPropertyChanging();
				this._IDHINHANH = value;
				this.SendPropertyChanged("IDHINHANH");
				this.OnIDHINHANHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGDAYDANG", DbType="Date")]
	public System.Nullable<System.DateTime> NGDAYDANG
	{
		get
		{
			return this._NGDAYDANG;
		}
		set
		{
			if ((this._NGDAYDANG != value))
			{
				this.OnNGDAYDANGChanging(value);
				this.SendPropertyChanging();
				this._NGDAYDANG = value;
				this.SendPropertyChanged("NGDAYDANG");
				this.OnNGDAYDANGChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDTAIKHOANGTINVIEN", DbType="Int")]
	public System.Nullable<int> IDTAIKHOANGTINVIEN
	{
		get
		{
			return this._IDTAIKHOANGTINVIEN;
		}
		set
		{
			if ((this._IDTAIKHOANGTINVIEN != value))
			{
				this.OnIDTAIKHOANGTINVIENChanging(value);
				this.SendPropertyChanging();
				this._IDTAIKHOANGTINVIEN = value;
				this.SendPropertyChanged("IDTAIKHOANGTINVIEN");
				this.OnIDTAIKHOANGTINVIENChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIABAN", DbType="NVarChar(MAX)")]
	public string GIABAN
	{
		get
		{
			return this._GIABAN;
		}
		set
		{
			if ((this._GIABAN != value))
			{
				this.OnGIABANChanging(value);
				this.SendPropertyChanging();
				this._GIABAN = value;
				this.SendPropertyChanged("GIABAN");
				this.OnGIABANChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_GIAGIAM", DbType="NVarChar(MAX)")]
	public string GIAGIAM
	{
		get
		{
			return this._GIAGIAM;
		}
		set
		{
			if ((this._GIAGIAM != value))
			{
				this.OnGIAGIAMChanging(value);
				this.SendPropertyChanging();
				this._GIAGIAM = value;
				this.SendPropertyChanged("GIAGIAM");
				this.OnGIAGIAMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TENPHIM", DbType="NVarChar(MAX)")]
	public string TENPHIM
	{
		get
		{
			return this._TENPHIM;
		}
		set
		{
			if ((this._TENPHIM != value))
			{
				this.OnTENPHIMChanging(value);
				this.SendPropertyChanging();
				this._TENPHIM = value;
				this.SendPropertyChanged("TENPHIM");
				this.OnTENPHIMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNGPHIM", DbType="NVarChar(MAX)")]
	public string NOIDUNGPHIM
	{
		get
		{
			return this._NOIDUNGPHIM;
		}
		set
		{
			if ((this._NOIDUNGPHIM != value))
			{
				this.OnNOIDUNGPHIMChanging(value);
				this.SendPropertyChanging();
				this._NOIDUNGPHIM = value;
				this.SendPropertyChanged("NOIDUNGPHIM");
				this.OnNOIDUNGPHIMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MAPHONG", DbType="NVarChar(MAX)")]
	public string MAPHONG
	{
		get
		{
			return this._MAPHONG;
		}
		set
		{
			if ((this._MAPHONG != value))
			{
				this.OnMAPHONGChanging(value);
				this.SendPropertyChanging();
				this._MAPHONG = value;
				this.SendPropertyChanged("MAPHONG");
				this.OnMAPHONGChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_XUATCHIEU", DbType="NVarChar(MAX)")]
	public string XUATCHIEU
	{
		get
		{
			return this._XUATCHIEU;
		}
		set
		{
			if ((this._XUATCHIEU != value))
			{
				this.OnXUATCHIEUChanging(value);
				this.SendPropertyChanging();
				this._XUATCHIEU = value;
				this.SendPropertyChanged("XUATCHIEU");
				this.OnXUATCHIEUChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_VIDEOS", DbType="NVarChar(MAX)")]
	public string VIDEOS
	{
		get
		{
			return this._VIDEOS;
		}
		set
		{
			if ((this._VIDEOS != value))
			{
				this.OnVIDEOSChanging(value);
				this.SendPropertyChanging();
				this._VIDEOS = value;
				this.SendPropertyChanged("VIDEOS");
				this.OnVIDEOSChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANHPHIM", DbType="NVarChar(MAX)")]
	public string HINHANHPHIM
	{
		get
		{
			return this._HINHANHPHIM;
		}
		set
		{
			if ((this._HINHANHPHIM != value))
			{
				this.OnHINHANHPHIMChanging(value);
				this.SendPropertyChanging();
				this._HINHANHPHIM = value;
				this.SendPropertyChanged("HINHANHPHIM");
				this.OnHINHANHPHIMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIM_KHUYENMAI", Storage="_KHUYENMAIs", ThisKey="IDCACBOPHIM", OtherKey="IDCACBOPHIM")]
	public EntitySet<KHUYENMAI> KHUYENMAIs
	{
		get
		{
			return this._KHUYENMAIs;
		}
		set
		{
			this._KHUYENMAIs.Assign(value);
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HINHANH_PHIM", Storage="_HINHANH", ThisKey="IDHINHANH", OtherKey="IDHINHANH", IsForeignKey=true)]
	public HINHANH HINHANH
	{
		get
		{
			return this._HINHANH.Entity;
		}
		set
		{
			HINHANH previousValue = this._HINHANH.Entity;
			if (((previousValue != value) 
						|| (this._HINHANH.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._HINHANH.Entity = null;
					previousValue.PHIMs.Remove(this);
				}
				this._HINHANH.Entity = value;
				if ((value != null))
				{
					value.PHIMs.Add(this);
					this._IDHINHANH = value.IDHINHANH;
				}
				else
				{
					this._IDHINHANH = default(Nullable<int>);
				}
				this.SendPropertyChanged("HINHANH");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
	
	private void attach_KHUYENMAIs(KHUYENMAI entity)
	{
		this.SendPropertyChanging();
		entity.PHIM = this;
	}
	
	private void detach_KHUYENMAIs(KHUYENMAI entity)
	{
		this.SendPropertyChanging();
		entity.PHIM = null;
	}
}

[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHUYENMAI")]
public partial class KHUYENMAI : INotifyPropertyChanging, INotifyPropertyChanged
{
	
	private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
	
	private int _IDKHUYENMAI;
	
	private string _CHUDEKHUYENMAI;
	
	private string _MUCUUDAI;
	
	private string _NOIDUNG;
	
	private System.DateTime _NGAYBANHANH;
	
	private System.DateTime _NGAYKETTHUC;
	
	private System.Nullable<int> _IDCACBOPHIM;
	
	private System.Nullable<int> _IDHINHANH;
	
	private string _HINHANHKHUYENMAI;
	
	private EntityRef<HINHANH> _HINHANH;
	
	private EntityRef<PHIM> _PHIM;
	
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDKHUYENMAIChanging(int value);
    partial void OnIDKHUYENMAIChanged();
    partial void OnCHUDEKHUYENMAIChanging(string value);
    partial void OnCHUDEKHUYENMAIChanged();
    partial void OnMUCUUDAIChanging(string value);
    partial void OnMUCUUDAIChanged();
    partial void OnNOIDUNGChanging(string value);
    partial void OnNOIDUNGChanged();
    partial void OnNGAYBANHANHChanging(System.DateTime value);
    partial void OnNGAYBANHANHChanged();
    partial void OnNGAYKETTHUCChanging(System.DateTime value);
    partial void OnNGAYKETTHUCChanged();
    partial void OnIDCACBOPHIMChanging(System.Nullable<int> value);
    partial void OnIDCACBOPHIMChanged();
    partial void OnIDHINHANHChanging(System.Nullable<int> value);
    partial void OnIDHINHANHChanged();
    partial void OnHINHANHKHUYENMAIChanging(string value);
    partial void OnHINHANHKHUYENMAIChanged();
    #endregion
	
	public KHUYENMAI()
	{
		this._HINHANH = default(EntityRef<HINHANH>);
		this._PHIM = default(EntityRef<PHIM>);
		OnCreated();
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKHUYENMAI", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
	public int IDKHUYENMAI
	{
		get
		{
			return this._IDKHUYENMAI;
		}
		set
		{
			if ((this._IDKHUYENMAI != value))
			{
				this.OnIDKHUYENMAIChanging(value);
				this.SendPropertyChanging();
				this._IDKHUYENMAI = value;
				this.SendPropertyChanged("IDKHUYENMAI");
				this.OnIDKHUYENMAIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CHUDEKHUYENMAI", DbType="NVarChar(MAX)")]
	public string CHUDEKHUYENMAI
	{
		get
		{
			return this._CHUDEKHUYENMAI;
		}
		set
		{
			if ((this._CHUDEKHUYENMAI != value))
			{
				this.OnCHUDEKHUYENMAIChanging(value);
				this.SendPropertyChanging();
				this._CHUDEKHUYENMAI = value;
				this.SendPropertyChanged("CHUDEKHUYENMAI");
				this.OnCHUDEKHUYENMAIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MUCUUDAI", DbType="NVarChar(MAX)")]
	public string MUCUUDAI
	{
		get
		{
			return this._MUCUUDAI;
		}
		set
		{
			if ((this._MUCUUDAI != value))
			{
				this.OnMUCUUDAIChanging(value);
				this.SendPropertyChanging();
				this._MUCUUDAI = value;
				this.SendPropertyChanged("MUCUUDAI");
				this.OnMUCUUDAIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NOIDUNG", DbType="NVarChar(1000) NOT NULL", CanBeNull=false)]
	public string NOIDUNG
	{
		get
		{
			return this._NOIDUNG;
		}
		set
		{
			if ((this._NOIDUNG != value))
			{
				this.OnNOIDUNGChanging(value);
				this.SendPropertyChanging();
				this._NOIDUNG = value;
				this.SendPropertyChanged("NOIDUNG");
				this.OnNOIDUNGChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYBANHANH", DbType="DateTime NOT NULL")]
	public System.DateTime NGAYBANHANH
	{
		get
		{
			return this._NGAYBANHANH;
		}
		set
		{
			if ((this._NGAYBANHANH != value))
			{
				this.OnNGAYBANHANHChanging(value);
				this.SendPropertyChanging();
				this._NGAYBANHANH = value;
				this.SendPropertyChanged("NGAYBANHANH");
				this.OnNGAYBANHANHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NGAYKETTHUC", DbType="DateTime NOT NULL")]
	public System.DateTime NGAYKETTHUC
	{
		get
		{
			return this._NGAYKETTHUC;
		}
		set
		{
			if ((this._NGAYKETTHUC != value))
			{
				this.OnNGAYKETTHUCChanging(value);
				this.SendPropertyChanging();
				this._NGAYKETTHUC = value;
				this.SendPropertyChanged("NGAYKETTHUC");
				this.OnNGAYKETTHUCChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDCACBOPHIM", DbType="Int")]
	public System.Nullable<int> IDCACBOPHIM
	{
		get
		{
			return this._IDCACBOPHIM;
		}
		set
		{
			if ((this._IDCACBOPHIM != value))
			{
				if (this._PHIM.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDCACBOPHIMChanging(value);
				this.SendPropertyChanging();
				this._IDCACBOPHIM = value;
				this.SendPropertyChanged("IDCACBOPHIM");
				this.OnIDCACBOPHIMChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHINHANH", DbType="Int")]
	public System.Nullable<int> IDHINHANH
	{
		get
		{
			return this._IDHINHANH;
		}
		set
		{
			if ((this._IDHINHANH != value))
			{
				if (this._HINHANH.HasLoadedOrAssignedValue)
				{
					throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
				}
				this.OnIDHINHANHChanging(value);
				this.SendPropertyChanging();
				this._IDHINHANH = value;
				this.SendPropertyChanged("IDHINHANH");
				this.OnIDHINHANHChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HINHANHKHUYENMAI", DbType="NVarChar(MAX)")]
	public string HINHANHKHUYENMAI
	{
		get
		{
			return this._HINHANHKHUYENMAI;
		}
		set
		{
			if ((this._HINHANHKHUYENMAI != value))
			{
				this.OnHINHANHKHUYENMAIChanging(value);
				this.SendPropertyChanging();
				this._HINHANHKHUYENMAI = value;
				this.SendPropertyChanged("HINHANHKHUYENMAI");
				this.OnHINHANHKHUYENMAIChanged();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="HINHANH_KHUYENMAI", Storage="_HINHANH", ThisKey="IDHINHANH", OtherKey="IDHINHANH", IsForeignKey=true)]
	public HINHANH HINHANH
	{
		get
		{
			return this._HINHANH.Entity;
		}
		set
		{
			HINHANH previousValue = this._HINHANH.Entity;
			if (((previousValue != value) 
						|| (this._HINHANH.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._HINHANH.Entity = null;
					previousValue.KHUYENMAIs.Remove(this);
				}
				this._HINHANH.Entity = value;
				if ((value != null))
				{
					value.KHUYENMAIs.Add(this);
					this._IDHINHANH = value.IDHINHANH;
				}
				else
				{
					this._IDHINHANH = default(Nullable<int>);
				}
				this.SendPropertyChanged("HINHANH");
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.AssociationAttribute(Name="PHIM_KHUYENMAI", Storage="_PHIM", ThisKey="IDCACBOPHIM", OtherKey="IDCACBOPHIM", IsForeignKey=true, DeleteRule="CASCADE")]
	public PHIM PHIM
	{
		get
		{
			return this._PHIM.Entity;
		}
		set
		{
			PHIM previousValue = this._PHIM.Entity;
			if (((previousValue != value) 
						|| (this._PHIM.HasLoadedOrAssignedValue == false)))
			{
				this.SendPropertyChanging();
				if ((previousValue != null))
				{
					this._PHIM.Entity = null;
					previousValue.KHUYENMAIs.Remove(this);
				}
				this._PHIM.Entity = value;
				if ((value != null))
				{
					value.KHUYENMAIs.Add(this);
					this._IDCACBOPHIM = value.IDCACBOPHIM;
				}
				else
				{
					this._IDCACBOPHIM = default(Nullable<int>);
				}
				this.SendPropertyChanged("PHIM");
			}
		}
	}
	
	public event PropertyChangingEventHandler PropertyChanging;
	
	public event PropertyChangedEventHandler PropertyChanged;
	
	protected virtual void SendPropertyChanging()
	{
		if ((this.PropertyChanging != null))
		{
			this.PropertyChanging(this, emptyChangingEventArgs);
		}
	}
	
	protected virtual void SendPropertyChanged(String propertyName)
	{
		if ((this.PropertyChanged != null))
		{
			this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
		}
	}
}
#pragma warning restore 1591
